version: "3.9"

services:
  server:
    build: ./
    ports:
      - "8080:8080"
  frontend:
    image: keny0cell/cloud:front
    ports:
      - "80:8080"
    depends_on:
      - server
    environment:
       - VUE_APP_BASE_URL=http://localhost:8080