version: "3.9"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db-data:

services:
  server:
    build: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .db-env
    networks:
      - backend
      - frontend
    depends_on:
      - db
  db:
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    env_file:
      - .db-env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
  frontend:
    image: keny0cell/cloud:front
    ports:
      - "80:8080"
    networks:
      - frontend
    depends_on:
      - server
    environment:
       - VUE_APP_BASE_URL="http://frontend:8080"