version: "3.9"

networks:
  backend:
    driver: bridge

volumes:
  db-data:

services:
  server:
    build: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .db-env
    networks:
      - backend
    depends_on:
      - db
  db:
    image: arm64v8/postgres
    ports:
      - "5432:5432"
    env_file:
      - .db-env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend