server:
  port: 8080

spring:
  config:
    import: optional:classpath:/env.properties
  datasource:
    username: "${DB_USER}"
    password: "${DB_PASS}"
    driver-class-name: org.h2.Driver
    url: "${DB_URL}"
    hikari:
      connection-init-sql: "SET SCHEMA ${DB_NAME}"
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yml"
    default-schema: "${DB_NAME}"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

jwt:
  public:
    key: classpath:/rsa.pub.pem
  private:
    key: classpath:/rsa.pem